language: java
jdk:
- oraclejdk7
branches:
  only:
  - master
env:
  global:
    secure: WmuTTbDn/SStME/rJhHBUVG3PxH4yOv0PdI8JdHN1n/VpLmxTot50LMD4JsqxrVPXqyMdqfufBhN2XokIwh1fvXqeusb6Z3jv2GJitK5in2T+/LTbP4cNYi6M6UQJqVWsLTtsm8j/XC7UUETQJ/2jJ93sLEPmaKLnGdzZjyqAjs=
script:
- mvn clean test
- mvn -f ./ajaxanywhere-testapp/pom.xml clean heroku:deploy-war
